import pygame


GAME_RES = (1280, 960)
GAME_FPS = (60)

WORLD_MOVE = 40

#FONTS
RES_FONT_TYPE = 'GALACTIC VANGUARDIAN NCV'
RES_FONT_SIZE = 57
RES_FONT_COLOR = (102, 51, 0)

INFO_FONT_TYPE = 'arial black'
INFO_FONT_SIZE = 20
INFO_FONT_COLOR = (102, 51, 0)

CASH_FONT_TYPE = 'arial black'
CASH_FONT_SIZE = 26
CASH_FONT_COLOR = (255, 255, 255)


# Game section
MAIN_MENU_POS = (0, 0)
MAIN_MENU_IMG = 'img/background/bg_menu.png'
MAIN_MENU_ACTIVE = True
GAME_POS = (0, 0)
GAME_IMG = 'img/background/frames.png'
GAME_ACTIVE = False
GAME_BG_POS = (0, 0)
GAME_BG_IMG = 'img/background/bg_game.png'
GAME_BG_ACTIVE = False
BETWEEN_LEVEL_UPGRADE_POS = (0, 0)
BETWEEN_LEVEL_UPGRADE_IMG = 'img/background/medzilevelovi_upgrade.png'
BETWEEN_LEVEL_UPGRADE_ACTIVE = False
CREDIT_POS = (0, 0)
CREDIT_IMG = 'img/background/credit.png'
CREDIT_ACTIVE = False



# BUTTONS MAIN MENU
B_NEW_GAME_POS = (457, 309)
B_NEW_GAME_IMG = 'img/buttons/newgame.png'
B_LOAD_POS = (B_NEW_GAME_POS[0], B_NEW_GAME_POS[1] + (pygame.image.load(B_NEW_GAME_IMG).get_height() + 30))
B_LOAD_IMG = 'img/buttons/load.png'
B_TUTORIAL_POS = (B_NEW_GAME_POS[0], B_LOAD_POS[1] + (pygame.image.load(B_LOAD_IMG).get_height() + 30))
B_TUTORIAL_IMG = 'img/buttons/turorial.png'
B_CREDIT_POS = (B_NEW_GAME_POS[0], B_TUTORIAL_POS[1] + (pygame.image.load(B_TUTORIAL_IMG).get_height() + 30))
B_CREDIT_IMG = 'img/buttons/credit.png'
B_AGAIN_IMG = 'img/buttons/again.png'
B_MAIN_MENU_IMG = 'img/buttons/main_menu.png'

# BUTTONS GAME
CREAT_THOR_POS = (163, 821)
CREAT_THOR_IMG = 'img/buttons/thor.png'
CREAT_ZEUS_POS = (35, 821)
CREAT_ZEUS_IMG = 'img/buttons/zeus.png'
CREAT_ODIN_POS = (291, 821)
CREAT_ODIN_IMG = 'img/buttons/odin.png'
RECOVERY_POS = (878, 821)
RECOVERY_IMG = 'img/buttons/recovery.png'
SPEED_POS = (1006, 821)
SPEED_IMG = 'img/buttons/speed.png'
STRONG_MISSILE_POS = (1134, 821)
STRONG_MISSILE_IMG = 'img/buttons/strong_missile.png'
B_IRON_UPGRADE_POS = (245, 68)
B_IRON_UPGRADE_IMG = 'img/buttons/source_upgrade.png'
B_CRYSTAL_UPGRADE_POS = (652, 68)
B_CRYSTAL_UPGRADE_IMG = 'img/buttons/source_upgrade.png'
B_URAN_UPGRADE_POS = (1042, 68)
B_URAN_UPGRADE_IMG = 'img/buttons/source_upgrade.png'

#Buttons for upgrade units properties
UNIVERSAL_IMG = 'img/buttons/buy.png'
ZEUS_UPGRADE_LIFE_POS = (358, 356)
ZEUS_UPGRADE_DAMAGE_POS = (ZEUS_UPGRADE_LIFE_POS[0], ZEUS_UPGRADE_LIFE_POS[1] + 55)
ZEUS_UPGRADE_DISTANCE_POS = (ZEUS_UPGRADE_LIFE_POS[0], ZEUS_UPGRADE_DAMAGE_POS[1] + 55)
THOR_UPGRADE_LIFE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 327, ZEUS_UPGRADE_LIFE_POS[1])
THOR_UPGRADE_DAMAGE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 327, THOR_UPGRADE_LIFE_POS[1] + 55)
THOR_UPGRADE_DISTANCE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 327, THOR_UPGRADE_DAMAGE_POS[1] + 55)
ODIN_UPGRADE_LIFE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 651, ZEUS_UPGRADE_LIFE_POS[1])
ODIN_UPGRADE_DAMAGE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 651, ODIN_UPGRADE_LIFE_POS[1] + 55)
ODIN_UPGRADE_DISTANCE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 651, ODIN_UPGRADE_DAMAGE_POS[1] + 55)
BASE_UPGRADE_LIFE_POS = (ZEUS_UPGRADE_LIFE_POS[0], 696)
SPEC_PROP_HEALING_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 327, BASE_UPGRADE_LIFE_POS[1])
SPEC_PROP_PLUS_DAMAGE_POS = (ZEUS_UPGRADE_LIFE_POS[0] + 651, BASE_UPGRADE_LIFE_POS[1])
MAIN_MENU_UP_SC_POS = (527, 800)
SAVE_GAME_POS = (203, 800)
SAVE_GAME_IMG = 'img/buttons/save_game.png'
NEXT_MISSION_POS = (851,800)
NEXT_MISSION_IMG = 'img/buttons/next_level.png'

#Buttons for tutorial
PAGE_PLUS_POS = (915, 399)
PAGE_PLUS_IMG = 'img/buttons/button_right.png'
PAGE_MINUS_POS = (PAGE_PLUS_POS[0] - 626, PAGE_PLUS_POS[1])
PAGE_MINUS_IMG = 'img/buttons/button_left.png'
BACK_MAIN_MENU_POS = (1020, 708)
BACK_MAIN_MENU_IMG = 'img/buttons/main_menu.png'

# Info panels
IRON_PANEL_POS = (90, 10)
IRON_PANEL_IMG = 'img/others/iron.png'
CRYSTAL_PANEL_POS = (492, 10)
CRYSTAL_PANEL_IMG = 'img/others/crystal.png'
URAN_PANEL_POS = (884, 10)
URAN_PANEL_IMG = 'img/others/uran.png'
INFO_PANEL_POS = (450, 809)
INFO_PANEL_IMG = 'img/others/info_panel.png'

# resources
IRON_INIT_COUNT_MINING = 1
IRON_INIT_STOCK = 1
IRON_SPEED_MINIG = 20
IRON_UP_PRICE_IRON = 10
IRON_UP_PRICE_CRYSTAL = 7
IRON_UP_PRICE_URAN = 4
IRON_UPGRADING_TIME = 300

CRYSTAL_INIT_COUNT_MINING = 1
CRYSTAL_INIT_STOCK = 1
CRYSTAL_SPEED_MINIG = 20
CRYSTAL_UP_PRICE_IRON = 12
CRYSTAL_UP_PRICE_CRYSTAL = 8
CRYSTAL_UP_PRICE_URAN = 6
CRYSTAL_UPGRADING_TIME = 360

URAN_INIT_COUNT_MINING = 1
URAN_INIT_STOCK = 1
URAN_SPEED_MINIG = 20
URAN_UP_PRICE_IRON = 15
URAN_UP_PRICE_CRYSTAL = 10
URAN_UP_PRICE_URAN = 8
URAN_UPGRADING_TIME = 420

# Bases
PLAYER_BASE_IMG = 'img/others/player_base.png'
PLAYER_BASE_POS = (10, 619)
PLAYER_BASE_LIVE = 1000
PLAYER_BASE_LIVE_MAX = 1000
PLAYER_BASE_BAR_W = 120
PLAYER_BASE_BAR_H = 20

ENEMY_BASE_IMG = 'img/others/enemy_base.png'
ENEMY_BASE_POS = (2240, 619)
ENEMY_BASE_LIVE = 1000
ENEMY_BASE_LIVE_MAX = 1000
ENEMY_BASE_BAR_W = 120
ENEMY_BASE_BAR_H = 20

# Player units
ZEUS_POS = (100, 600)
ZEUS_IMG = 'img/others/zeus.png'
ZEUS_NAME = 'zeus'
ZEUS_TRAINING_TIME = 40
ZEUS_SPEED_MOVE = 3
ZEUS_SHOOT_POWER = 20
ZEUS_SHOOT_SPEED = 60
ZEUS_LIVE = 300
ZEUS_SHOOTING_DISTANCE = 550
ZEUS_IRON_PRICE = 8
ZEUS_CRYSTAL_PRICE = 6
ZEUS_URAN_PRICE = 6
ZEUS_ALREADY_MOVED = False
ZEUS_UPGRADE_LIFE = 30
ZEUS_UPGRADE_DAMAGE = 30
ZEUS_UPGRADE_DISTANCE = 30



THOR_POS = (100, 600)
THOR_IMG = 'img/others/thor.png'
THOR_NAME = 'thor'
THOR_TRAINING_TIME = 60
THOR_SPEED_MOVE = 3
THOR_SHOOT_POWER = 70
THOR_SHOOT_SPEED = 80
THOR_LIVE = 400
THOR_SHOOTING_DISTANCE = 600
THOR_IRON_PRICE = 12
THOR_CRYSTAL_PRICE = 8
THOR_URAN_PRICE = 6
THOR_ALREADY_MOVED = False
THOR_UPGRADE_LIFE = 30
THOR_UPGRADE_DAMAGE = 30
THOR_UPGRADE_DISTANCE = 30

ODIN_POS = (100, 600)
ODIN_IMG = 'img/others/odin.png'
ODIN_NAME = 'odin'
ODIN_TRAINING_TIME = 40
ODIN_SPEED_MOVE = 3
ODIN_SHOOT_POWER = 150
ODIN_SHOOT_SPEED = 111
ODIN_LIVE = 400
ODIN_SHOOTING_DISTANCE = 500
ODIN_IRON_PRICE = 12
ODIN_CRYSTAL_PRICE = 10
ODIN_URAN_PRICE = 8
ODIN_ALREADY_MOVED = False
ODIN_UPGRADE_LIFE = 30
ODIN_UPGRADE_DAMAGE = 30
ODIN_UPGRADE_DISTANCE = 30

# Enemy units
ENEM_POSITION = (2240, 565)
ENEM_IMAGE_PATH = 'img/others/enem.png'
ENEM_LIVE = 200
ENEM_SHOOT_POWER = 50
ENEM_SPEED_SHOOTING = 60
ENEM_LVL_ONE = [200, 2400, 3600, 5400, 7000, 7500, 9500]

ENEL_POSITION = (2240, 565)
ENEL_IMAGE_PATH = 'img/others/enel.png'
ENEL_LIVE = 400
ENEL_SHOOT_POWER = 40
ENEL_SPEED_SHOOTING = 84
ENEL_LVL_ONE = [3000, 6000, 9000, 15000]

ENEX_POSITION = (2240, 565)
ENEX_IMAGE_PATH = 'img/others/enex.png'
ENEX_LIVE = 800
ENEX_SHOOT_POWER = 80
ENEX_SPEED_SHOOTING = 135
ENEX_LVL_ONE = [4000, 7000, 10500, 13000, 14000]

#Projectile
PROJECTILE_IMG_R = 'img/others/projectil1.png'
PROJECTILE_IMG_B = 'img/others/projectil2.png'
PROJECTILE_IMG_G = 'img/others/projectil3.png'
PROJECTILE_POS = (0, 0)